Documentation:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
    Max: 110
